[package]
name = "wasm-snake-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.87"
wasm-pack = "0.12.1"

[lib]
crate-type = ["cdylib"]
